name: JAE Exam

on:
    push

jobs:
    creation-text-file:
      runs-on: ubuntu-latest

      steps:
        - name: Creation a file
          run: echo "Test text">testFile.txt
        - name: Check
          run: cat testFile.txt
        - name: Upload
          uses: actions/upload-artifact@v7
          with:
            name: myArti
            path: testFile.txt
    checking-file:
      runs-on: ubuntu-latest
      
      needs: creation-text-file
      steps:
        - name: Download
          uses: actions/download-artifact@v8
          with:
            name: myArti
            path: testFile.txt
        - name: View of file
          run: cat testFile.txt







    # создает текстовый файл с содержимым
    # выводет содержимое файла в консоль